language: ruby

rvm:
  - ruby-head
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx-19mode
  - rbx-18mode
  - jruby-head
  - jruby-18mode

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: rbx-18mode
    - rvm: jruby-head
    - rvm: jruby-18mode

before_install:
  - gem install bundler
